baseURL = "https://cloudadventures.fskelly.com"
title = "Fletcher's Tech Blog"
copyright = "Copyright © 2019–2021, Fletcher Kelly; all rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

ignoreErrors = ["error-missing-instagram-accesstoken"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Fletcher Kelly"
  description = "Fletcher's Cloud Journey."
  homepageImage = "/images/homepage-image2.png"
  dateFormat = "January 2, 2006"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
#    email = "example@example.com"
#    facebook = "https://facebook.com"
    twitter = "https://twitter.com/fskelly"
    linkedin = "https://linkedin.com/in/fletcherkelly"
#    stack-overflow = "https://stackoverflow.com"
#    instagram = "https://stackoverflow.com"
    github = "https://github.com/fskelly"
#    weibo = "https://www.weibo.com"
#    medium = "https://medium.com"
#    pinterest = "https://pinterest.com"
#    reddit = "https://reddit.com"
#    gitlab = "https://gitlab.com"
#    mastodon = "https://mastodon.social"
#    keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
