name: Blob Storage Copy - NorthEndLab

on:
    push:
        branches: [ northendLab ]
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches: [northendLab]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Az Accoutn set
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az account set --subscription 949ef534-07f5-4138-8b79-aae16a71310c

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_PREPROD }} --auth-mode key -d '$web' -s $GITHUB_WORKSPACE/public
#            az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} --auth-mode key -d '$web' -s .
#    - name: Purge CDN endpoint
#      uses: azure/CLI@v1
#      with:
#        azcliversion: 2.0.72
#        inlineScript: |
#           az cdn endpoint purge --content-paths  "/*" --profile-name "CDN_PROFILE_NAME" --name "CDN_ENDPOINT" --resource-group "RESOURCE_GROUP"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
      
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: superbrothers/close-pull-request@v3
        with:
        # Optional. Post a issue comment just before closing a pull request.
                comment: "Closing PR"
